PROCESS BEFORE OUTPUT.
  MODULE STATUS_0700.
  MODULE CHANGE_SCREEN_0700.
*
PROCESS AFTER INPUT.
  MODULE USER_COMMAND_0700.

PROCESS ON VALUE-REQUEST.
  FIELD gd-double_click MODULE gd_double_click_f4.
