PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC9000'
  MODULE TC9000_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC9000_CHANGE_COL_ATTR.
  LOOP AT   GT_PLANE
       INTO GS_PLANE
       WITH CONTROL TC9000
       CURSOR TC9000-CURRENT_LINE.
*&SPWIZARD:   MODULE TC9000_CHANGE_FIELD_ATTR
  ENDLOOP.

  MODULE pbo_9000.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC9000'
  LOOP AT GT_PLANE.
    CHAIN.
      FIELD GS_PLANE-PLANETYPE.
      FIELD GS_PLANE-SEATSMAX.
      FIELD GS_PLANE-CON_UNIT.
      FIELD GS_PLANE-TANKCAP.
      FIELD GS_PLANE-CAP_UNIT.
      FIELD GS_PLANE-WEIGHT.
      FIELD GS_PLANE-WEI_UNIT.
      FIELD GS_PLANE-SPAN_UNIT.
      FIELD GS_PLANE-LENG_UNIT.
      FIELD GS_PLANE-OP_SPEED.
      FIELD GS_PLANE-SPEED_UNIT.
      FIELD GS_PLANE-PRODUCER.
      FIELD GS_PLANE-SEATSMAX_B.
      FIELD GS_PLANE-SEATSMAX_F.
      MODULE TC9000_MODIFY ON CHAIN-REQUEST.
    endchain.
  ENDLOOP.
*&SPWIZARD: MODULE TC9000_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC9000_CHANGE_COL_ATTR.

 MODULE pai_9000.
