PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC9000'
  MODULE TC9000_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC9000_CHANGE_COL_ATTR.
  LOOP AT   GT_STRAVELAG
       INTO GS_STRAVELAG
       WITH CONTROL TC9000
       CURSOR TC9000-CURRENT_LINE.
*&SPWIZARD:   MODULE TC9000_CHANGE_FIELD_ATTR
  ENDLOOP.

 MODULE pbo_9000.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC9000'
  LOOP AT GT_STRAVELAG.
    CHAIN.
      FIELD GS_STRAVELAG-AGENCYNUM.
      FIELD GS_STRAVELAG-NAME.
      FIELD GS_STRAVELAG-STREET.
      FIELD GS_STRAVELAG-POSTBOX.
      FIELD GS_STRAVELAG-POSTCODE.
      FIELD GS_STRAVELAG-CITY.
      FIELD GS_STRAVELAG-COUNTRY.
      FIELD GS_STRAVELAG-REGION.
      FIELD GS_STRAVELAG-TELEPHONE.
      FIELD GS_STRAVELAG-URL.
      FIELD GS_STRAVELAG-LANGU.
      FIELD GS_STRAVELAG-CURRENCY.
    endchain.
  ENDLOOP.
*&SPWIZARD: MODULE TC9000_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC9000_CHANGE_COL_ATTR.

 MODULE pai_9000.
