interface ZIF_SALES_ORDER_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ROOT,
 CREATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FD1809F1FA4F8F01578',
 DELETE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FD1809F1FA4F8F09578',
 LOCK_ROOT                      TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FD1809F1FA4F8EF5578',
 SAVE_ROOT                      TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FD1809F1FA4F8F11578',
 UNLOCK_ROOT                    TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FD1809F1FA4F8EF9578',
 UPDATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FD1809F1FA4F8F05578',
 VALIDATE_ROOT                  TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FD1809F1FA4F8F0D578',
      END OF ROOT,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ROOT,
        BEGIN OF LOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ROOT,
        BEGIN OF UNLOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ROOT,
      END OF ROOT,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ROOT,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FD1809F1FA4F8EF3578',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FD1809F1FA4F8EEF578',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FD1809F1FA4F8EFF578',
      END OF ROOT,
      BEGIN OF ROOT_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FD1809F1FA4F8F17578',
      END OF ROOT_LOCK,
      BEGIN OF ROOT_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FD1809F1FA4F8F15578',
      END OF ROOT_MESSAGE,
      BEGIN OF ROOT_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FD1809F1FA4F8F19578',
      END OF ROOT_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ROOT,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ROOT,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '00505683AF6F1FD1809F1FA4F8EE5578' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZBO_SALES_ORDER' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ROOT                           TYPE /BOBF/OBM_NODE_KEY VALUE '00505683AF6F1FD1809F1FA4F8EE9578',
 ROOT_LOCK                      TYPE /BOBF/OBM_NODE_KEY VALUE '00505683AF6F1FD1809F1FA4F8EF1578',
 ROOT_MESSAGE                   TYPE /BOBF/OBM_NODE_KEY VALUE '00505683AF6F1FD1809F1FA4F8EED578',
 ROOT_PROPERTY                  TYPE /BOBF/OBM_NODE_KEY VALUE '00505683AF6F1FD1809F1FA4F8EFD578',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ROOT,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  SOID                           TYPE STRING VALUE 'SOID',
  ERDAT                          TYPE STRING VALUE 'ERDAT',
  ERZET                          TYPE STRING VALUE 'ERZET',
  CUSTOMERID                     TYPE STRING VALUE 'CUSTOMERID',
  STATUS                         TYPE STRING VALUE 'STATUS',
      END OF ROOT,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ROOT,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '00505683AF6F1FD1809F1FA4F8EEB578',
      END OF ROOT,
    END OF SC_NODE_CATEGORY .
endinterface.
