interface ZIF_DD_CHAMADOS_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZDD_CHAMADOS,
 CREATE_ZDD_CHAMADOS            TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FD180B76351A5F6180C',
 DELETE_ZDD_CHAMADOS            TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FD180B76351A5F6980C',
 LOCK_ZDD_CHAMADOS              TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FD180B76351A5F5580C',
 SAVE_ZDD_CHAMADOS              TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FD180B76351A5F7180C',
 UNLOCK_ZDD_CHAMADOS            TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FD180B76351A5F5980C',
 UPDATE_ZDD_CHAMADOS            TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FD180B76351A5F6580C',
 VALIDATE_ZDD_CHAMADOS          TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FD180B76351A5F6D80C',
      END OF ZDD_CHAMADOS,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZDD_CHAMADOS,
        BEGIN OF LOCK_ZDD_CHAMADOS,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZDD_CHAMADOS,
        BEGIN OF UNLOCK_ZDD_CHAMADOS,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZDD_CHAMADOS,
      END OF ZDD_CHAMADOS,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZDD_CHAMADOS,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '00505683AF6F1FD180B76379E75B980C',
      END OF ZDD_CHAMADOS,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZDD_CHAMADOS,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FD180B76351A5F5380C',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FD180B76351A5F4F80C',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FD180B76351A5F5F80C',
      END OF ZDD_CHAMADOS,
      BEGIN OF ZDD_CHAMADOS_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FD180B76351A5F7780C',
      END OF ZDD_CHAMADOS_LOCK,
      BEGIN OF ZDD_CHAMADOS_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FD180B76351A5F7580C',
      END OF ZDD_CHAMADOS_MESSAGE,
      BEGIN OF ZDD_CHAMADOS_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FD180B76351A5F7980C',
      END OF ZDD_CHAMADOS_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZDD_CHAMADOS,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZDD_CHAMADOS,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '00505683AF6F1FD180B76351A5F4580C' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZDD_CHAMADOS' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZDD_CHAMADOS,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '00505683AF6F1FD180B76379E75BB80C',
 SET_CHAMADO_ID                 TYPE /BOBF/DET_KEY VALUE '00505683AF6F1FD180B7C5EDEFA1D90D',
      END OF ZDD_CHAMADOS,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZDD_CHAMADOS                   TYPE /BOBF/OBM_GROUP_KEY VALUE '00505683AF6F1FD180B7639D1068780C',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZDD_CHAMADOS                   TYPE /BOBF/OBM_NODE_KEY VALUE '00505683AF6F1FD180B76351A5F4980C',
 ZDD_CHAMADOS_LOCK              TYPE /BOBF/OBM_NODE_KEY VALUE '00505683AF6F1FD180B76351A5F5180C',
 ZDD_CHAMADOS_MESSAGE           TYPE /BOBF/OBM_NODE_KEY VALUE '00505683AF6F1FD180B76351A5F4D80C',
 ZDD_CHAMADOS_PROPERTY          TYPE /BOBF/OBM_NODE_KEY VALUE '00505683AF6F1FD180B76351A5F5D80C',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZDD_CHAMADOS,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  CHAMADOID                      TYPE STRING VALUE 'CHAMADOID',
  ASSUNTO                        TYPE STRING VALUE 'ASSUNTO',
  DESCRICAO                      TYPE STRING VALUE 'DESCRICAO',
  SOLICIANTEID                   TYPE STRING VALUE 'SOLICIANTEID',
  STATUS                         TYPE STRING VALUE 'STATUS',
      END OF ZDD_CHAMADOS,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZDD_CHAMADOS,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '00505683AF6F1FD180B76351A5F4B80C',
      END OF ZDD_CHAMADOS,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZDD_CHAMADOS,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE '00505683AF6F1FD180B7639D1064780C',
 VALIDATE                       TYPE /BOBF/VAL_KEY VALUE '00505683AF6F1FD180B79754FB9ED892',
      END OF ZDD_CHAMADOS,
    END OF SC_VALIDATION .
endinterface.
