interface ZIF_DD_CHAMADOS_O2_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZDD_CHAMADOS_O2,
 CREATE_ZDD_CHAMADOS_O2         TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FE180BFF4587CACEF90',
 DELETE_ZDD_CHAMADOS_O2         TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FE180BFF4587CAD6F90',
 LOCK_ZDD_CHAMADOS_O2           TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FE180BFF4587CAC2F90',
 SAVE_ZDD_CHAMADOS_O2           TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FE180BFF4587CADEF90',
 UNLOCK_ZDD_CHAMADOS_O2         TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FE180BFF4587CAC6F90',
 UPDATE_ZDD_CHAMADOS_O2         TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FE180BFF4587CAD2F90',
 VALIDATE_ZDD_CHAMADOS_O2       TYPE /BOBF/ACT_KEY VALUE '00505683AF6F1FE180BFF4587CADAF90',
      END OF ZDD_CHAMADOS_O2,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZDD_CHAMADOS_O2,
        BEGIN OF LOCK_ZDD_CHAMADOS_O2,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZDD_CHAMADOS_O2,
        BEGIN OF UNLOCK_ZDD_CHAMADOS_O2,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZDD_CHAMADOS_O2,
      END OF ZDD_CHAMADOS_O2,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZDD_CHAMADOS_O2,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '00505683AF6F1FE180BFF488F2CBAF90',
      END OF ZDD_CHAMADOS_O2,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZDD_CHAMADOS_O2,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FE180BFF4587CAC0F90',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FE180BFF4587CABCF90',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FE180BFF4587CACCF90',
      END OF ZDD_CHAMADOS_O2,
      BEGIN OF ZDD_CHAMADOS_O2_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FE180BFF4587CAE4F90',
      END OF ZDD_CHAMADOS_O2_LOCK,
      BEGIN OF ZDD_CHAMADOS_O2_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FE180BFF4587CAE2F90',
      END OF ZDD_CHAMADOS_O2_MESSAGE,
      BEGIN OF ZDD_CHAMADOS_O2_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505683AF6F1FE180BFF4587CAE6F90',
      END OF ZDD_CHAMADOS_O2_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZDD_CHAMADOS_O2,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZDD_CHAMADOS_O2,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '00505683AF6F1FE180BFF4587CAB2F90' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZDD_CHAMADOS_O2' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZDD_CHAMADOS_O2,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '00505683AF6F1FE180BFF488F2CBCF90',
      END OF ZDD_CHAMADOS_O2,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZDD_CHAMADOS_O2                TYPE /BOBF/OBM_GROUP_KEY VALUE '00505683AF6F1FE180BFF488F2D00F90',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZDD_CHAMADOS_O2                TYPE /BOBF/OBM_NODE_KEY VALUE '00505683AF6F1FE180BFF4587CAB6F90',
 ZDD_CHAMADOS_O2_LOCK           TYPE /BOBF/OBM_NODE_KEY VALUE '00505683AF6F1FE180BFF4587CABEF90',
 ZDD_CHAMADOS_O2_MESSAGE        TYPE /BOBF/OBM_NODE_KEY VALUE '00505683AF6F1FE180BFF4587CABAF90',
 ZDD_CHAMADOS_O2_PROPERTY       TYPE /BOBF/OBM_NODE_KEY VALUE '00505683AF6F1FE180BFF4587CACAF90',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZDD_CHAMADOS_O2,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  CHAMADOID                      TYPE STRING VALUE 'CHAMADOID',
  ASSUNTO                        TYPE STRING VALUE 'ASSUNTO',
  DESCRICAO                      TYPE STRING VALUE 'DESCRICAO',
  SOLICIANTEID                   TYPE STRING VALUE 'SOLICIANTEID',
  STATUS                         TYPE STRING VALUE 'STATUS',
      END OF ZDD_CHAMADOS_O2,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZDD_CHAMADOS_O2,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '00505683AF6F1FE180BFF4587CAB8F90',
      END OF ZDD_CHAMADOS_O2,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZDD_CHAMADOS_O2,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE '00505683AF6F1FE180BFF488F2CC0F90',
      END OF ZDD_CHAMADOS_O2,
    END OF SC_VALIDATION .
endinterface.
