*&---------------------------------------------------------------------*
*& Report Z_SCREEN
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT Z_SCREEN.

SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE text-001.
    PARAMETERS P_PNOME TYPE CHAR35.
    PARAMETERS P_UNOME TYPE CHAR35.
    PARAMETERS P_EMAIL TYPE CHAR255.
SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE text-001.
    PARAMETERS P_CEP    TYPE CHAR10.
    PARAMETERS P_RUA    TYPE CHAR35.
    PARAMETERS P_NUMERO TYPE CHAR10.
    PARAMETERS P_BAIRRO TYPE CHAR255.
    PARAMETERS P_CIDADE TYPE CHAR255.
    PARAMETERS P_UF     TYPE CHAR255.
SELECTION-SCREEN END OF BLOCK b2.

SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME TITLE text-001.
    PARAMETERS P_ativo TYPE flag.
SELECTION-SCREEN END OF BLOCK b3.

START-OF-SELECTION.
  BREAK-POINT.
  CALL SCREEN 1001.
*  FORMA DE POPUP
  CALL SCREEN 1001 STARTING AT 1 1 ENDING AT 80 12.
  BREAK-POINT.
  MESSAGE 'PROGRAMA EXECUTADO' TYPE 'S'.

INCLUDE z_screen_e01.
