"Name: \PR:SAPMV45A\FO:USEREXIT_MOVE_FIELD_TO_VBAK\SE:BEGIN\EI
ENHANCEMENT 0 ZABAP_PLAYLIST.
**HOW TO USE MODIFY VBAK-LIFSK WITH A USER EXIT - TCODE VA01 EXAMPLE
*  IF vbak-vbeln IS INITIAL AND SY-ucomm = 'SICH' AND KUAGV-kunnr = '1000272'.
*    VBAK-LIFSK = '01'.
*  ENDIF.

*  vbak-zzfield = xxxx-zzfield2.
ENDENHANCEMENT.
